export enum CatalogItemCondition {
  NEW = 'NEW',
  LIKE_NEW = 'LIKE_NEW',
  USED_GOOD = 'USED_GOOD',
  USED_FAIR = 'USED_FAIR',
  FOR_PARTS = 'FOR_PARTS',
}

export enum CatalogItemPublicationStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  IN_NEGOTIATION = 'IN_NEGOTIATION',
  RESERVED = 'RESERVED',
  EXCHANGED = 'EXCHANGED',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum ExchangeProposalStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum ExchangeMatchStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NOT_CONCRETED = 'NOT_CONCRETED',
  EXPIRED = 'EXPIRED',
}

export const ACTIVE_NEGOTIATION_PROPOSAL_STATUSES = [
  ExchangeProposalStatus.PENDING,
] as const;

export const ACTIVE_NEGOTIATION_MATCH_STATUSES = [
  ExchangeMatchStatus.ACTIVE,
] as const;

export const FREE_ACTIVE_NEGOTIATION_LIMIT_PER_ITEM = 3;

export const FREE_MAX_ACTIVE_OFFERS_PER_PUBLICATION = 5;
export const FREE_MAX_DISTINCT_REQUESTERS_PER_PUBLICATION = 3;
